In [29]:
import torch

In [30]:
w = torch.ones(3, 512)
a = torch.ones(2 * 512, 3)

In [31]:
h = torch.FloatTensor([[1, 1, 1], [2, 2, 2]])

In [32]:
h = h @ w

In [33]:
h.shape

torch.Size([2, 512])

In [34]:
N = h.size(0)

In [35]:
w_h_i = h.repeat(1, N).view(N * N, -1)

In [36]:
print(w_h_i)

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [6., 6., 6.,  ..., 6., 6., 6.],
        [6., 6., 6.,  ..., 6., 6., 6.]])


In [37]:
w_h_j = h.repeat(N, 1)

In [38]:
print(w_h_j)

tensor([[3., 3., 3.,  ..., 3., 3., 3.],
        [6., 6., 6.,  ..., 6., 6., 6.],
        [3., 3., 3.,  ..., 3., 3., 3.],
        [6., 6., 6.,  ..., 6., 6., 6.]])


In [39]:
cat = torch.cat([w_h_i, w_h_j], dim=1).view(N, -1, 2 * 512)

In [40]:
print(cat[0][1])

tensor([3., 3., 3.,  ..., 6., 6., 6.])


In [41]:
e = torch.nn.functional.leaky_relu(torch.matmul(cat, a).squeeze(2))

In [42]:
e

tensor([[[3072., 3072., 3072.],
         [4608., 4608., 4608.]],

        [[4608., 4608., 4608.],
         [6144., 6144., 6144.]]])

In [43]:
adj = torch.FloatTensor([
  [1, 0],
  [1, 1],
])

adj = adj.view(*adj.shape, 1)

In [44]:
zero_vec = torch.zeros_like(e)

In [45]:
zero_vec.shape

torch.Size([2, 2, 3])

In [46]:
e.shape

torch.Size([2, 2, 3])

In [47]:
torch.where(adj > 0, e, zero_vec)

tensor([[[3072., 3072., 3072.],
         [   0.,    0.,    0.]],

        [[4608., 4608., 4608.],
         [6144., 6144., 6144.]]])

In [48]:
for tensor in torch.where(adj > 0, e, zero_vec):
  print(tensor)

tensor([[3072., 3072., 3072.],
        [   0.,    0.,    0.]])
tensor([[4608., 4608., 4608.],
        [6144., 6144., 6144.]])


In [49]:
adj.shape

torch.Size([2, 2, 1])

In [50]:
torch.FloatTensor([
  [1, 0],
  [0, 1]
]).view(2, 2, 1)

tensor([[[1.],
         [0.]],

        [[0.],
         [1.]]])